export const plus = 'plus';
export const projects = 'home'; // we're using the home icon for the projects section
export const goals = 'goals';
export const charts = 'chart';
export const settings = 'settings';
export const leftArrow = 'left_arrow';
export const rightArrow = 'right_arrow';
export const checkmark = 'checkmark';
export const clock = 'clock';
export const calendar = 'calendar';
export const playButton = 'play_button';
export const up_arrow = 'up_arrow';
export const important = 'important';
export const edit = 'edit';
export const cancel = 'cancel';
export const trash = 'trash';
