import React from 'react';
import {Scene, Router} from 'react-native-router-flux';
import ProjectNavigator from './ProjectNavigator';
import TimeIsLife from './TimeIsLife';
import {
  CreateProject,
  CreateTask,
  EditProject,
  ManageProjectHours,
  AddProjectHours,
  ManageSettings,
  ManageWeeklyGoals,
  ProjectList,
  ProjectGoals,
  ProjectTask,
  ProjectTimer,
  ProjectHours,
  ProjectHoursWorked,
  TaskList,
  Maxims,
  ViewProjectCharts,
} from './ProjectActions';

const RouterComponent = () => (
  <Router>
    <Scene key="root">
      <Scene
        key="timeIsLife"
        component={TimeIsLife}
        title="TimeIsLife"
        hideNavBar
        initial
      />
      <Scene
        key="projectNavigator"
        component={ProjectNavigator}
        title="ProjectNavigator"
        hideNavBar
      />
      <Scene
        key="createProject"
        component={CreateProject}
        title="CreateProject"
        hideNavBar
      />
      <Scene
        key="createTask"
        component={CreateTask}
        title="CreateTask"
        hideNavBar
      />
      <Scene
        key="editProject"
        component={EditProject}
        title="EditProject"
        hideNavBar
      />
      <Scene
        key="manageProjectHours"
        component={ManageProjectHours}
        title="ManageProjectHours"
        hideNavBar
      />
      <Scene
        key="projectGoals"
        component={ProjectGoals}
        title="ProjectGoals"
        hideNavBar
      />
      <Scene
        key="projectTask"
        component={ProjectTask}
        title="ProjectTask"
        hideNavBar
      />
      <Scene
        key="manageSettings"
        component={ManageSettings}
        title="ManageSettings"
        hideNavBar
      />
      <Scene
        key="manageWeeklyGoals"
        component={ManageWeeklyGoals}
        title="ManageWeeklyGoals"
        hideNavBar
      />
      <Scene
        key="maxims"
        component={Maxims}
        title="Maxims"
        hideNavBar
      />
      <Scene
        key="projectList"
        component={ProjectList}
        title="ProjectList"
        hideNavBar
      />
      <Scene
        key="projectTimer"
        component={ProjectTimer}
        title="ProjectTimer"
        hideNavBar
      />
      <Scene
        key="projectHours"
        component={ProjectHours}
        title="ProjectHours"
        hideNavBar
      />
      <Scene
        key="projectHoursWorked"
        component={ProjectHoursWorked}
        title="ProjectHoursWorked"
        hideNavBar
      />
      <Scene
        key="viewProjectCharts"
        component={ViewProjectCharts}
        title="ViewProjectCharts"
        hideNavBar
      />
      <Scene
        key="taskList"
        component={TaskList}
        title="TaskList"
        hideNavBar
      />
      <Scene
        key="addProjectHours"
        component={AddProjectHours}
        title="addProjectHours"
        hideNavBar
      />
    </Scene>
  </Router>
);

export default RouterComponent;
